### ISSUE TITLE
Scene Checklist

### ISSUE THREAD

**Issue by JGEatwell** [ThallasTV/HelloWorldMcomp#20]
- [ ] Refine "starting area" with more objects, lighting and **Cloud** planes for added effect.

- [x] Study required assets from the **Book of the dead** asset package.

- [x] Re-design the Terrain by using Planes instead of a Terrain to prevent VR from breaking.

- [x] Refine the rain system.

All this will be finished by Friday.
